# Generated by Django 5.2 on 2025-05-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('authority_id', models.CharField(max_length=100)),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed')], max_length=50)),
                ('response_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'success'), ('canceled', 'canceled')], max_length=50)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.payment')),
            ],
        ),
    ]
